@url = http://127.0.0.1:8021
@controller = http://127.0.0.1:3000
###
GET {{controller}}/connections
###
DELETE {{controller}}/connections
###
GET {{controller}}/status
###
GET {{controller}}/connection-info
###
GET {{controller}}/set-globals
###
DELETE {{controller}}/connections
###
GET {{controller}}/schemas
###
GET {{controller}}/credential-definitions
###
GET {{controller}}/webhooks/
###
GET {{controller}}/credential-definitions
###
GET {{controller}}/issue-credential
###