@url = http://127.0.0.1:8021
@controller = http://127.0.0.1:3002
###
GET {{controller}}/connections
###
DELETE {{controller}}/connections
###
GET {{controller}}/connection-status
###
GET {{controller}}/connection-info
###
GET {{controller}}/set-connectionid
###
DELETE {{controller}}/connections
###
GET {{controller}}/schemas
###
GET {{controller}}/credential-definitions
###
GET {{controller}}/webhooks/
###
GET {{controller}}/credential-definitions
###
GET {{controller}}/issue-credential
###
DELETE {{controller}}/request-proof-v1
###
GET {{controller}}/request-proof-v1
###
DELETE {{controller}}/request-proof-v2
###