@url = http://127.0.0.1:8021
@controller = http://127.0.0.1:3000
@docker_controller = https://92db-123-136-28-130.ngrok-free.app
@remote_controller = https://2333-123-136-28-130.ngrok-free.app

###
GET {{remote_controller}}/connections

###
DELETE  {{remote_controller}}/Connections