@url = http://127.0.0.1:8021
@controller = http://127.0.0.1:3000
@remote_controller = https://2333-123-136-28-130.ngrok-free.app

###
POST {{url}}/endpoint
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com"
}
###
POST {{controller}}/mobile-agent-connection 
Content-Type: application/json

{
    "memoNameData": "winxp",
    "emailData": "winxp@gmail.com"
}
###
GET {{controller}}/connections

###
GET {{remote_controller}}/connections

###
DELETE  {{remote_controller}}/Connections
###

DELETE {{controller}}/connections


###
GET {{controller}}/schemas
###
GET {{controller}}/credential-definitions
###
GET {{controller}}/issue-credential
###
POST {{controller}}/issue-credential
Content-Type: application/json

{
    "indy_field": {
                "cred_def_id":"VGXTHfUFKGWbnm4jkvaWCC:3:CL:232227:Grade",
                "issuer_did":"VGXTHfUFKGWbnm4jkvaWCC" ,
                "schema_id": "VGXTHfUFKGWbnm4jkvaWCC:2:Grade:1.0",
                "schema_issuer_did": "VGXTHfUFKGWbnm4jkvaWCC",
                "schema_name": "Grade",
                "schema_version": "1.0"

    },
    "attrs": [
        {"name":"name", "value":"Arie"},
        {"name":"id", "value":"20101498"},
        {"name":"grade", "value":"D"}
    ]
}


###
DELETE {{controller}}/issue-credential
###
GET {{remote_controller}}/issue-credential
###
DELETE {{remote_controller}}/issue-credential
###
GET {{remote_controller}}/credentials
###
DELETE {{remote_controller}}/credentials
###
POST {{controller}}/present-proof
Content-Type: application/json

{
    "attr_name":"id",
    "attr_val":"20101334",
    "cred_def_id":"VGXTHfUFKGWbnm4jkvaWCC:3:CL:232227:Grade"

}
### 
GET {{controller}}/present-proof
###
DELETE {{controller}}/present-proof
###
GET {{remote_controller}}/present-proof
###
DELETE {{remote_controller}}/present-proof
###
POST {{remote_controller}}/send-proof
Content-Type: application/json

{
    "cred_id":"56291836-4c50-421c-b3f6-bd3f4acda0a9",
    "pres_ex_id":"4ceb578c-1a58-4317-ac9e-2fa46da70a2d"

}
###
POST {{controller}}/verify
###
POST {{remote_controller}}/verify
###
GET {{controller}}/public-did
###
GET {{remote_controller}}/public-did
###
POST {{controller}}/request-proof-v1
Content-Type: application/json

{
    "attr_name":"id",
    "attr_val":"20101334",
    "schema_name":"Grade"

}
###
GET {{controller}}/request-proof-v1
###
DELETE  {{controller}}/request-proof-v1
###